/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import PaletteImage.PaletteImage;
import java.awt.Window;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tebaomang
 */
public class PSNR extends javax.swing.JFrame {
    
    private PaletteImage image1;
    private PaletteImage image2;

    /**
     * Creates new form PSNR2
     */
    public PSNR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OriginalLabel = new javax.swing.JLabel();
        SecretLabel = new javax.swing.JLabel();
        ChoosePicture1Button = new javax.swing.JButton();
        ChoosePicture2Button = new javax.swing.JButton();
        EmbeFileButton = new javax.swing.JButton();
        psnrLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PSNR Calculator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        OriginalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OriginalLabel.setText("Gimme a picture");

        SecretLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SecretLabel.setText("Gimme another picture");

        ChoosePicture1Button.setText("Choose Picture 1");
        ChoosePicture1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoosePicture1ButtonActionPerformed(evt);
            }
        });

        ChoosePicture2Button.setText("Choose Picture 2");
        ChoosePicture2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoosePicture2ButtonActionPerformed(evt);
            }
        });

        EmbeFileButton.setText("Calculate PSNR");
        EmbeFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmbeFileButtonActionPerformed(evt);
            }
        });

        psnrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        psnrLabel.setText("Press Calculate PSNR");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(ChoosePicture1Button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .add(SecretLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(OriginalLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(ChoosePicture2Button, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(psnrLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(EmbeFileButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(OriginalLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ChoosePicture1Button)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(SecretLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ChoosePicture2Button)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(psnrLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EmbeFileButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChoosePicture1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoosePicture1ButtonActionPerformed
        // TODO add your handling code here:
        try {
            image1 = new PaletteImage();
            if (image1!=null) OriginalLabel.setText(image1.getWidth()+"x"+image1.getHeight()+" pixels");
        } catch (IOException ex) {
            Logger.getLogger(PSNR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChoosePicture1ButtonActionPerformed

    private void ChoosePicture2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoosePicture2ButtonActionPerformed
        // TODO add your handling code here:
        try {
            image2 = new PaletteImage();
            if (image2!=null) SecretLabel.setText(image2.getWidth()+"x"+image2.getHeight()+" pixels");
        } catch (IOException ex) {
            Logger.getLogger(PSNR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChoosePicture2ButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        List<Window> visibleWindows = new ArrayList<Window>();
            for(Window w: Window.getWindows()){
                if(w.isShowing()){
                    visibleWindows.add(w);
                }
            }
        if(visibleWindows.isEmpty()) System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void EmbeFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmbeFileButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(image1!=null){
                if(image2!=null){
                    if(image1.getWidth()==image2.getWidth()&&image1.getHeight()==image2.getHeight()){
                        double psnr = image1.PSNR(image2);
                        psnrLabel.setText(""+psnr);
                    }  else JOptionPane.showMessageDialog(new JFrame(), "Two pictures selected do not have the same dimensions", "ERROR", JOptionPane.ERROR_MESSAGE);
                }  else JOptionPane.showMessageDialog(new JFrame(), "Picture 2 not selected", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else JOptionPane.showMessageDialog(new JFrame(), "Picture 1 not selected", "ERROR", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception ex) {
            Logger.getLogger(Embeder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmbeFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PSNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PSNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PSNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PSNR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PSNR().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChoosePicture1Button;
    private javax.swing.JButton ChoosePicture2Button;
    private javax.swing.JButton EmbeFileButton;
    private javax.swing.JLabel OriginalLabel;
    private javax.swing.JLabel SecretLabel;
    private javax.swing.JLabel psnrLabel;
    // End of variables declaration//GEN-END:variables
}
